### ISSUE TITLE
Add new clipped item to TOP of list instead of bottom?

### ISSUE THREAD

**Issue by ghost** [rosulek/workflowy-clipper#1]
Hi

This Chrome extension is really great. Thanks for making it!

I have one feature suggestion. I always add new list items to the top of my Workflowy lists, so the newest items I add are always the first ones I see in a list. Is this a feature you could consider adding as an option to your extension? If not, could you perhaps point me in the right direction for adding this feature myself? Or you can tell me to just go figure it out for myself too. 😄

**Comment by rosulek** [comment]
It is not a configurable option (at the moment -- would be nice eventually). But it is an easy change to the source code, if you're able to build the extension yourself. Just change priority from 9999 to 0 in [this line](https://github.com/rosulek/workflowy-clipper/blob/master/src/background.js#L72). This is from memory, so let me know if you encounter problems.

**Comment by ghost** [comment]
Thanks for the answer. I've actually figured out quite a good workaround. I've set up a "Clipper inbox" list where I put everything, then when I've got a lot of items in that list I move them in bulk to the top of my main list. That works pretty well.
